### PR TITLE
add support for amavis

### PR DESCRIPTION
**Pull request by rdoorn**
add support for amavis antivirus scanner

### CODE REVIEW

**Comment by cmluciano** [comment]
Hi rdoorn. I'm not sure if adding amavis support is in the scope of this cookbook. This seems to be a great addition to a wrapper cookbook where you know exactly what your options will be, and you can inherit the values in the master.cf

**Comment by rdoorn** [comment]
Hi @cmluciano 
Would it not be easier if the support was a simple flag in the attributes, rather then having everyone who uses amavis write a wrapper cookbook  to rewrite/rewind this postfix config file?
that would also make it easier to get new features/changes in the postfix cookbook, without having to change the rewritten files in your wrapper.
Eventualle we could also make it auto-detect the use of the amavis cookbook, and if loaded, then include this additional config. that would make the cookbook more flexible and automated.
Kind Regard,
Ronald

**Comment by jtimberman** [comment]
I'm :-1:. The right thing to do is to have the master.cf be attribute generated [like main.cf](https://github.com/opscode-cookbooks/postfix/blob/master/templates/default/main.cf.erb). Such settings would be in `node['postfix']['master']`.

**Comment by rdoorn** [comment]
agreed that would be even nicer, would be one hell of a long attribute though ;-)

**Comment by cmluciano** [comment]
That is true. My wrapper attribute file is pretty long because postfix has so many options. This cookbook aims to only include options that are common to most instances.

**Pull request closed without merging**
